version: '3.8'

services:
  jenkins:
    build: .
    container_name: jenkins-local
    ports:
      - "3711:8080"
      - "50000:50000"
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    user: root 

volumes:
  jenkins:
