apiVersion: v1
kind: Service
metadata:
  name: pizza-helper-frontend
spec:
  type: LoadBalancer
  selector:
    app: pizza-helper-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
