apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-helper-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pizza-helper-db
  template:
    metadata:
      labels:
        app: pizza-helper-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: pizza_user
        - name: POSTGRES_PASSWORD
          value: pizza_password
        - name: POSTGRES_DB
          value: pizza_db
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
