apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-helper-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pizza-helper-frontend
  template:
    metadata:
      labels:
        app: pizza-helper-frontend
    spec:
      containers:
      - name: frontend
        image: orbitroll/pizza-helper-frontend:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
